name: Push Docker DEV Image
on:
  workflow_dispatch: # Allow manual trigger
  workflow_run:
    workflows: ["Omnia Tests"] # Depend on success from tests
    types:
      - completed
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Build and Publish Deployer Image to Github Packages
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only if tests passed
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./docker/deployer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Build only on push to master
          tags: ghcr.io/chronicleprotocol/deployer:latest,ghcr.io/chronicleprotocol/deployer:dev
      
      # - name: Build and Publish SSB Server Image to Github Packages
      #   uses: docker/build-push-action@v2.7.0
      #   with:
      #     context: .
      #     file: ./docker/ssb-server/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: ${{ github.event_name != 'pull_request' }} # Build only on push to master
      #     tags: ghcr.io/chronicleprotocol/ssb_dev:${{ steps.prep.outputs.version }}

      - name: Build and Publish Omnia DEV Image to Github Packages
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only if tests passed
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Build only on push to master
          tags: ghcr.io/chronicleprotocol/omnia:dev